#rabbitmq配置
spring:
  application:
      name: service-portal
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
#  cloud:
#      config:
#        uri: http://10.12.97.45:8769
#        profile: dev
#        label: master
#        discovery:
#          enabled: true
#          service-id: ace-config-server
#      bus:
#        trace:
#          enabled: true
#        enabled: true
  datasource:
#    name: test
    url: jdbc:oracle:thin:@${ORACLE_HOST:10.11.24.136}:${ORACLE_PORT:1521}:arltr
    username: lark_portal
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    ###优化数据库连接池配置,该配置支持2000并发
    druid:
      max-active: 18
      initial-size: 3
      min-idle: 3
      max-wait: 250000
      time-between-eviction-runs-millis: 250000
      min-evictable-idle-time-millis: 120000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      filter: stat,wall,log4j
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x' from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  rabbitmq:
    #需要修改地址
    host: 10.11.24.135
    port: 5672
    username: hollykunge
    password: 123456
    virtual-host: /
    ###使用rabbitmq消息发送确认机制
    publisher-confirms: true
#开启消费者（程序出现异常的情况下会）进行重试,
    listener:
      simple:
        #开启手动ack
        acknowledge-mode: manual
        retry:
        #重试机制适用于门户服务数据库暂时24秒内连接不上等情况
          enabled: true
        #最大重试次数
          max-attempts: 8
        #重试间隔次数
          initial-interval: 3000ms

mybatis:
    basepackage: com.github.hollykunge.security.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

#ribbon负载
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true


#websocket:
#  tio:
#    server:
#      #websocket监听端口
#      port: 9520
#      #协议名称
#      name: portalcase
#      #响应客户端字符集
#      charset: utf-8
#      #设置心跳超时时间
#      heartbeat:
#        timeout: 60000

server:
  port: 8770
  profiles:
    active: dev

#springcloud默认配置中心
#spring:
#  application:
#    name: service-portal
#  cloud:
#    config:
#      uri: http://10.12.97.45:8769
#      profile: dev
#      label: master
#      discovery:
#        enabled: true
#        service-id: ace-config-server
#    bus:
#      trace:
#        enabled: true
#      enabled: true

#eruka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
        ###向注册中心上注册自己
      register-with-eureka: true
        ###是否需要从eureka上获取注册信息
      fetch-registry: true
#      register-with-eureka: false
#      #是否需要从eureka上获取注册信息
#      fetch-registry: false

#log日志
logging:
  #运行日志
  level:
    root: info
  file: ${user.home}/logs/portal/portal.log

####卡片宽度，高度
portal:
  card:
    w: 1
    h: 5
druid:
  enabled: true
  whiteip: 127.0.0.1
  blackip: 192.168.1.1
  loginUsername: admin
  loginPassword: 123456






